insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-1', 'thread', 'sfioasfiaifiasfiiifaifsi', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-2', 'DUMMY TITLE - 1', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-3', 'DUMMY TITLE - 2', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-4', 'DUMMY TITLE - 3', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', '105171178520467521319', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-5', 'DUMMY TITLE - 4', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-6', 'DUMMY TITLE - 5', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-7', 'DUMMY TITLE - 6', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', '105171178520467521319', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-8', 'DUMMY TITLE - 7', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', '105171178520467521319', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-9', 'DUMMY TITLE - 8', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-10', 'DUMMY TITLE - 9', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-11', 'DUMMY TITLE - 10', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-12', 'DUMMY TITLE - 11', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-13', 'DUMMY TITLE - 12', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-14', 'DUMMY TITLE - 13', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', 'user-1', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-15', 'DUMMY TITLE - 14', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', '105171178520467521319', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-16', 'DUMMY TITLE - 15', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', '105171178520467521319', 'benny indra');
insert into THREADS (id, title, content, google_id, created_by) values ('user-thread-17', 'DUMMY TITLE - 16', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', '105171178520467521319', 'benny indra');

insert into THREAD_POSTS (id, title, content, google_id, thread_id, created_by) values ('user-thread-post-17', 'DUMMY TITLE PP - 1', 'Download this ebook to learn how a causal approach to artificial intelligence for operations (AIOps), combined with broad and deep observability and continuous runtime application security, helps financial services institutions overcome the increasingly complex IT challenges they face as they transform their business to win customer trust and loyalty to grow while optimizing efficiencies and reducing costs.', '105171178520467521319', 'user-thread-17', 'benny indra');
